# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: action-maven-publish
      # You may pin to the exact commit or the version.
      # uses: samuelmeuli/action-maven-publish@201a45a3f311b2ee888f252ba9f4194257545709
      uses: samuelmeuli/action-maven-publish@v1.4.0
      with:
        # Username (not email!) for your Nexus repository manager account
        nexus_username: ${{ secrets.NEXUS_CENTRAL_USERNAME }}
        # Password for your Nexus account
        nexus_password: ${{ secrets.NEXUS_CENTRAL_PASSWORD }}
        # Nexus server ID as specified in your project's `nexus-staging-maven-plugin` and `distributionManagement` configurations
        server_id: ossrh
